name: CI

on:
  push:
    branches: [ master ] 
    pull_request: [ master ]
    
jobs:
  build: 
    runs_on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    - name: Run a one-line scripts
      run: echo Hello, World!
      
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
